### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by LateForMyTrain** [maxxscholten/nyc-train-sign#3]
Node.js server listening on 8080
(node:27063) UnhandledPromiseRejectionWarning: FetchError: request to http://datamine.mta.info/mta_esi.php?feed_id=1&key=removedmyapikey failed, reason: getaddrinfo ENOTFOUND datamine.mta.info datamine.mta.info:80
    at ClientRequest.<anonymous> (/home/pi/nyc-train-sign/Server/node/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:27063) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27063) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I tried a few things but nothing has worked for me. Any idea what I should do next? Still learning.

**Comment by maxxscholten** [comment]
Looks like maybe the api irk has changed since I made it. Look into here: 

https://api.mta.info/#/landing

Thanks,
Maxx

**Comment by LateForMyTrain** [comment]
Got it, I'll do my best. Thanks.
